[package]
name = "ph"
version = "0.1.0"
authors = ["Justin Pombrio <justinpombrio@cs.brown.edu>"]

[dependencies]
rocket = "*"
rocket_codegen = "*"
htmlescape = "*"
mustache = "*"
chrono = "*"

[dependencies.postgres]
version = "*"
features = ["with-chrono"]
